// <auto-generated />
namespace eRecarga.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdminUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201911212235117_AdminUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
